### ISSUE TITLE
Pass arguments to pip

### ISSUE THREAD

**Issue by OscartGiles** [paketo-buildpacks/pip-install#205]
## Describe the Enhancement

paketo-buildpacks/pip-install checks for the presence of `requirements.txt` and then install dependencies with pip. A fixed set of optional arguments are passed to [pip install](https://pip.pypa.io/en/stable/cli/pip_install/#options): https://github.com/paketo-buildpacks/pip-install/blob/e2f15c017d7d32e8d078c935b1fb11a53c0048e1/install_process.go#L74-L85

It would be useful to be able to **_pass additional optional arguments to pip via [environment variables](https://buildpacks.io/docs/app-developer-guide/environment-variables/)_**. For example, a user may want to provide [`--index-url`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-0) to provide an alternative Python Package Index. 

It may already be possible to pass arguments to pip by [including them in `requirements.txt`](https://pip.pypa.io/en/stable/reference/requirements-file-format/#requirements-file-format).  However, `--index-url` may contain secrets (e.g. for connecting to a private package index) which should not be in `requirements.txt`. 

Other pip arguments may be useful, including [`--requirement`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-r) (but note this will require changes to both detect and build phases). 

## Possible Solution

Allow passing environment variables (e.g. `BP_PIP_INDEX_URL`, `BP_PIP_REQUIREMENT`) which, if provided are appended to the pip arguments.

**Comment by robdimsdale** [comment]
hey @OscartGiles - sorry for the delay.

This sounds reasonable to me. I'd like to find a solution that is extensible but also intuitive to the user. I am wondering about enabling _additional_ arguments via `BP_PIP_EXTRA_INSTALL_ARGS`. I think that solves your `--index-url` case, as well as providing a framework for adding extra arguments beyond `--index-url`.

Alternatively, I think we could provide `BP_PIP_INSTALL_ARGS` and just override them all. That feels frustrating though, as the user would have to provide many arguments, most of which are redundant. They'd have to keep that up to date with our defaults as they change. I'd probably prefer to enable individual overrides of specific default values (like `BP_REQUIREMENTS_LOCATION` or similar) as the use-cases arise.

**Comment by hashlash** [comment]
+1, I'd love the option to specify the `requirements.txt` file location

**Comment by mnbao1975** [comment]
For now, there is another way to change the values for the command-line options that we can use pip.co. In the the Dockerfile you can copy your pip.conf to /etc. Here my Dockerfile for customizing a builder-image:

FROM gcr.io/paketo-buildpacks/builder:base
COPY platform /platform
COPY pip.conf /etc/

**Comment by robdimsdale** [comment]
Just following up on this, pip supports configuration via [environment variables](https://pip.pypa.io/en/stable/topics/configuration/#environment-variables) in addition to the `--flag` format.

What this means for the buildpack is that you can provide configuration via the environment. E.g. for `pack` you would do:

```
pack build --env PIP_SOME_VAR=<some-value> <app-name>
```

Which would be the same as `pip install --some-var=<some-value>`.

**Comment by hashlash** [comment]
Nice catch! Using the pip's env var config, it should be able to remove all of the hardcoded `requirements.txt` references and let the user set it using `PIP_REQUIREMENT` (with the default being `requirements.txt`) env var, right?

**Comment by robdimsdale** [comment]
> Using the pip's env var config, it should be able to remove all of the hardcoded requirements.txt references and let the user set it using PIP_REQUIREMENT (with the default being requirements.txt) env var, right?

I haven't tested that. It should work, assuming pip prioritizes the environment variable over the `-r` flag.

**Comment by hashlash** [comment]
@robdimsdale What I mean by removing the `requirements.txt` reference is updating the `pip-install` buildpack source code. Based on the [precedence docs](https://pip.pypa.io/en/stable/topics/configuration/#precedence-override-order), the CLI option will override the env var. Thus we need to remove the hardcoded `--requirement requirements.txt` to allow users to set the option via env var.

https://github.com/paketo-buildpacks/pip-install/blob/e2f15c017d7d32e8d078c935b1fb11a53c0048e1/install_process.go#L77-L78

I could make a draft PR, but it might take some time to resolve since I haven't been familiar with developing buildpacks. I'm eager to learn tho :)

**Comment by robdimsdale** [comment]
Ah, ok. That was the bit I didn't test. I didn't validate the precedence order.

I think we can repurpose this issue to scope it just to the `--requirements` flag. I think I'd like to leave the other CLI flags alone for now, and I think that leveraging pip's existing environment variable support for new flags (e.g. `PIP_EXTRA_INDEX_URL=<url>`) meets the other part of this request.

Does that seem reasonable to folks?

If so, then the next question becomes - does `pip` have built-in support for providing `--requirements` via an environment variable? (e.g. `PIP_REQUIREMENTS`). If so, this becomes fairly straightforward - set the environment of the pip-install process to include that value and remove the `--requirements` flag altogether. Default the value of the environment variable to `requirements.txt` if it wasn't provided by the user.

If there is no built-in support for this feature in pip, the solution looks similar but instead of using the existing env var name, we would create a new one (e.g. `BP_PIP_REQUIREMENTS_PATH`).

**Comment by hashlash** [comment]
I agree. Some existing hardcoded flags might need special treatment.

Btw, I've tried it on a fresh virtual environment, and `PIP_REQUIREMENT` works as expected.

```
(env) $ echo "django" > req.txt && PIP_REQUIREMENT=req.txt pip install
Collecting django (from -r req.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/22/af/979a4c610e727cc936c3db3d48cfcb3c270e106ff919f23fc1a27870ba00/Django-3.2.19-py3-none-any.whl
Requirement already satisfied: asgiref<4,>=3.3.2 in ./env/lib/python3.7/site-packages (from django->-r req.txt (line 1)) (3.7.2)
Requirement already satisfied: sqlparse>=0.2.2 in ./env/lib/python3.7/site-packages (from django->-r req.txt (line 1)) (0.4.4)
Requirement already satisfied: pytz in ./env/lib/python3.7/site-packages (from django->-r req.txt (line 1)) (2023.3)
Requirement already satisfied: typing-extensions>=4; python_version < "3.11" in ./env/lib/python3.7/site-packages (from asgiref<4,>=3.3.2->django->-r req.txt (line 1)) (4.6.3)
Installing collected packages: django
Successfully installed django-3.2.19
```

**Comment by robdimsdale** [comment]
Nice. Thanks for exploring that. So it looks like the solution would be to remove`--requirements` from the `pip install` invocation and replace it with `PIP_REQUIREMENT=<file>`. If the user didn't provide a value for `PIP_REQUIREMENT`, then we would default to `requirements.txt`.

Does that sound right to you? Are you willing and able to submit a PR for that?

**Comment by hashlash** [comment]
Exactly what I thought. Sure, I'll try to work on it this weekend
